name: flutter_design_patterns
description: Flutter Design Patterns Library

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.5.0
  flutter_markdown:
    git:
      url: https://github.com/flutter/flutter_markdown.git
      ref: master
  xml: ^3.5.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/markdown/
    - assets/images/adapter/
    - assets/images/singleton/
    - assets/images/template_method/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
