name: flutter_design_patterns
description: Flutter Design Patterns Library

version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  flutter_markdown: ^0.3.5
  xml: ^3.6.1
  faker: ^1.2.1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/data/
    - assets/markdown/
    - assets/images/abstract_factory/
    - assets/images/adapter/
    - assets/images/bridge/
    - assets/images/builder/
    - assets/images/command/
    - assets/images/composite/
    - assets/images/decorator/
    - assets/images/facade/
    - assets/images/factory_method/
    - assets/images/flyweight/
    - assets/images/interpreter/
    - assets/images/iterator/
    - assets/images/memento/
    - assets/images/prototype/
    - assets/images/proxy/
    - assets/images/singleton/
    - assets/images/state/
    - assets/images/strategy/
    - assets/images/template_method/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf
